run:
  timeout: 5m
  tests: false

issues:
  exclude-dirs:
    - docs
    - cmd/cobaltdb-bench
    - cmd/debug
    - cmd/demo
    - cmd/realworld-test

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused

linters-settings:
  gofmt:
    simplify: true
