run:
  timeout: 5m
  tests: false

issues:
  exclude-dirs:
    - docs
    - cmd/benchmark
    - cmd/cobaltdb-bench
    - cmd/debug
    - cmd/demo
    - cmd/demo-ecommerce
    - cmd/demo-full-sql-test
    - cmd/demo-integrity-test
    - cmd/demo-performance
    - cmd/demo-showcase
    - cmd/demo-zero-error-proof

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused

linters-settings:
  gofmt:
    simplify: true
